### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ppoetsma** [jmleglise/mylittle-domoticz#2]
Hi,

The errors below are produced by the script. I am using the script available at this point in time. When I enable debug logging I see the data I expect to see. But this script gives the errors below in the console.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "check_beacon_presence.py", line 134, in request_thread
    logging.critical(' %s Request Failed %s - %s' % (threading.current_thread(), e, url) )
TypeError: __str__ returned non-string (type Error)

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "check_beacon_presence.py", line 134, in request_thread
    logging.critical(' %s Request Failed %s - %s' % (threading.current_thread(), e, url) )
TypeError: __str__ returned non-string (type Error)
```

Regards,
Paul

**Comment by ppoetsma** [comment]
I found the cause. I use the secure (HTTPS) Domoticz URL but there's the standard self signed certificate and not a real trusted certificate. The Python script cannot handle this. What must be changed to the script?

**Comment by ppoetsma** [comment]
Found a quick fix to skip the certificate checking, until I have Let's Encrypt running:
`result = requests.get(url, verify = False, auth=(DOMOTICZ_USER, DOMOTICZ_PASS))`

**Comment by jmleglise** [comment]
Hi, 

Indeed, I use a letsencrypt certificate.
You have some howto here : http://www.domoticz.com/wiki/Native_secure_access_with_Lets_Encrypt
